name: Debug Secrets Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
      - name: Output Secrets
        run: |
          echo "ACR_USERNAME: '${{ secrets.ACR_USERNAME }}'"
          echo "ACR_PASSWORD: '${{ secrets.ACR_PASSWORD }}'"
