name: Minimal Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output Secrets
        run: |
          echo "ACR Username: '${{ secrets.ACR_USERNAME }}'"
          echo "ACR Password: '${{ secrets.ACR_PASSWORD }}'"
