jobs:
  debug-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      secrets: write
    steps:
      - name: Output Secrets
        run: |
          echo "ACR Username: '${{ secrets.ACR_USERNAME }}'"
          echo "ACR Password: '${{ secrets.ACR_PASSWORD }}'"
